(tests
 (names
  test_app
  test_actor
  test_at_uri
  test_auth
  test_car
  test_cid
  test_cohttp_client
  test_did_key
  test_did_plc
  test_did_web
  test_error
  test_feed
  test_firehose
  test_graph
  test_http_client
  test_http_method
  test_identity
  test_label
  test_lexicon
  test_moderation
  test_mst
  test_notification
  test_oauth
  test_request
  test_repo
  test_response
  test_server
  test_session
  test_sync
  test_syntax
  test_tid
  test_user
  test_blob
  test_blocks
  test_download_image
  test_xrpc)
 (libraries
  async
  core
  uri
  yojson
  ptime
  cohttp
  cohttp-lwt-unix
  cohttp-async
  h2
  httpaf
  httpaf-lwt-unix
  h2-lwt-unix
  lwt
  ssl
  jose
  lwt_ssl
  digestif
  mirage-crypto-ec
  mirage-crypto-rng.unix
  zarith
  ounit2
  atproto)
 (modules
  test_app
  test_actor
  test_at_uri
  test_auth
  test_car
  test_cid
  test_cohttp_client
  test_did_key
  test_did_plc
  test_did_web
  test_error
  test_feed
  test_firehose
  test_graph
  test_http_client
  test_http_method
  test_identity
  test_label
  test_lexicon
  test_moderation
  test_mst
  test_notification
  test_oauth
  test_request
  test_repo
  test_response
  test_server
  test_session
  test_sync
  test_syntax
  test_tid
  test_user
  test_blob
  test_blocks
  test_download_image
  test_xrpc))
