(tests
 (flags
  (:standard -w +33 -warn-error +33))
 (names
  test_app
  test_actor
  test_admin
  test_ageassurance
  test_at_uri
  test_auth
  test_base32
  test_base64url
  test_bookmark
  test_car
  test_chat
  test_cid
  test_cohttp_client
  test_contact
  test_did_key
  test_did_plc
  test_did_web
  test_draft
  test_embed
  test_error
  test_facet
  test_feed
  test_firehose
  test_germnetwork
  test_graph
  test_hash
  test_http_client
  test_http_method
  test_identity
  test_jetstream
  test_label
  test_labeler
  test_lexicon
  test_local_appview
  test_local_oauth
  test_local_ozone
  test_local_pds
  test_moderation
  test_mst
  test_notification
  test_oauth
  test_oauth_scope
  test_ozone
  test_request
  test_records
  test_repo
  test_repo_sync
  test_response
  test_server
  test_session
  test_site
  test_sync
  test_syntax
  test_temp
  test_tid
  test_unspecced
  test_user
  test_varint
  test_blob
  test_blocks
  test_download_image
  test_video
  test_xrpc)
 (libraries
  async
  core
  uri
  yojson
  ptime
  cohttp
  cohttp-lwt-unix
  cohttp-async
  h2
  httpaf
  httpaf-lwt-unix
  h2-lwt-unix
  lwt
  ssl
  jose
  lwt_ssl
  digestif
  mirage-crypto-ec
  mirage-crypto-rng.unix
  zarith
  ounit2
  threads
  unix
  atproto)
 (modules
  test_app
  test_actor
  test_admin
  test_ageassurance
  test_at_uri
  test_auth
  test_base32
  test_base64url
  test_bookmark
  test_car
  test_chat
  test_cid
  test_cohttp_client
  test_contact
  test_did_key
  test_did_plc
  test_did_web
  test_draft
  test_embed
  test_error
  test_facet
  test_feed
  test_firehose
  test_germnetwork
  test_graph
  test_hash
  test_http_client
  test_http_method
  test_identity
  test_jetstream
  test_label
  test_labeler
  test_lexicon
  test_local_appview
  test_local_oauth
  test_local_ozone
  test_local_pds
  test_moderation
  test_mst
  test_notification
  test_oauth
  test_oauth_scope
  test_ozone
  test_request
  test_records
  test_repo
  test_repo_sync
  test_response
  test_server
  test_session
  test_site
  test_sync
  test_syntax
  test_temp
  test_tid
  test_unspecced
  test_user
  test_varint
  test_blob
  test_blocks
  test_download_image
  test_video
  test_xrpc))
