(executable
 (name offline)
 (flags
  (:standard -w +33 -warn-error +33))
 (libraries atproto yojson)
 (modules offline))

(executable
 (name quickstart)
 (flags
  (:standard -w +33 -warn-error +33))
 (libraries atproto)
 (modules quickstart))

(rule
 (alias runtest)
 (action
  (run %{exe:offline.exe})))
