(include_subdirs unqualified)

(library
 (name atproto)
 (libraries
  async
  core
  uri
  yojson
  ptime
  cohttp
  cohttp-lwt-unix
  cohttp-async
  h2
  httpaf
  httpaf-lwt-unix
  h2-lwt-unix
  ssl
  jose
  lwt_ssl
  lwt)
 (preprocess
  (pps ppx_jane))
 (modules
  App
  Actor
  At_uri
  Auth
  Base32
  Car
  Cid
  Cohttp_client
  Dag_cbor
  Did_plc
  Embed
  Error
  Facet
  Feed
  Firehose
  Graph
  Http_client
  Http_method
  Identity
  Label
  Lexicon
  Moderation
  Notification
  Repo
  Request
  Response
  Server
  Session
  Sync
  User
  Varint))
