(include_subdirs unqualified)

(library
 (name atproto)
 (libraries
  async
  core
  uri
  yojson
  ptime
  cohttp
  cohttp-lwt-unix
  cohttp-async
  h2
  httpaf
  httpaf-lwt-unix
  h2-lwt-unix
  ssl
  jose
  lwt_ssl
  lwt
  digestif
  mirage-crypto-ec
  mirage-crypto-rng.unix
  zarith)
 (preprocess
  (pps ppx_jane))
 (modules
  Admin
  Ageassurance
  App
  Actor
  At_uri
  Auth
  Base32
  Base58
  Base64url
  Bookmark
  Car
  Chat
  Cid
  Client
  Cohttp_client
  Contact
  Dag_cbor
  Did_key
  Did_plc
  Did_web
  Draft
  Embed
  Error
  Facet
  Feed
  Firehose
  Graph
  Hash
  Http_client
  Http_method
  Identity
  Jetstream
  K256
  Label
  Labeler
  Lexicon
  Moderation
  Mst
  Notification
  Oauth
  Oauth_scope
  Ozone
  Records
  Repo
  Repo_sync
  Request
  Response
  Server
  Session
  Sync
  Syntax
  Temp
  Tid
  Unspecced
  User
  Varint
  Video
  Websocket
  Xrpc))
